
services:
  web:
    build: .
    container_name: projet_carrefour_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: projet_carrefour_db
    environment:
      POSTGRES_DB: carrefour_db
      POSTGRES_USER: carrefour_user
      POSTGRES_PASSWORD: carrefour_pass
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
