# Generated by Django 5.2 on 2025-10-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='est_present',
        ),
        migrations.AddField(
            model_name='employe',
            name='duree_pause',
            field=models.IntegerField(default=90, help_text='Durée de la pause en minutes (par défaut 1h30)'),
        ),
        migrations.AddField(
            model_name='employe',
            name='heure_debut_travail',
            field=models.TimeField(default='08:00', help_text='Heure de début de travail'),
        ),
        migrations.AddField(
            model_name='employe',
            name='heure_fin_travail',
            field=models.TimeField(default='17:00', help_text='Heure de fin de travail'),
        ),
        migrations.AddField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('PRESENT', 'Présent'), ('RETARD', 'En retard'), ('ABSENT', 'Absent')], default='ABSENT', max_length=20),
        ),
    ]
