# Generated by Django 5.2 on 2025-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0002_remove_presence_est_present_employe_duree_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='tolerance_retard',
            field=models.IntegerField(default=60, help_text="Tolérance en minutes avant d'être marqué absent (défaut: 60min)"),
        ),
    ]
