# Generated by Django 5.2 on 2025-10-16 13:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0003_presence_tolerance_retard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='heure_arrivee',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='heure_depart',
        ),
        migrations.AddField(
            model_name='presence',
            name='heure_derniere_depart',
            field=models.TimeField(blank=True, help_text='Dernière déconnexion de la journée', null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='heure_premiere_arrivee',
            field=models.TimeField(blank=True, help_text='Première connexion de la journée', null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='temps_actif_total',
            field=models.FloatField(default=0, help_text='Temps total actif en heures (somme de toutes les sessions)'),
        ),
        migrations.CreateModel(
            name='SessionPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure_connexion', models.TimeField()),
                ('heure_deconnexion', models.TimeField(blank=True, null=True)),
                ('duree_active', models.FloatField(default=0, help_text='Durée en heures')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de Présence',
                'verbose_name_plural': 'Sessions de Présence',
                'ordering': ['-date', '-heure_connexion'],
            },
        ),
    ]
