# Generated by Django 5.2.7 on 2025-10-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0004_remove_presence_heure_arrivee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='produits',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='caissier',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='client',
        ),
        migrations.DeleteModel(
            name='LigneVente',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Vente',
        ),
    ]
