# Generated by Django 5.2 on 2025-10-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0004_remove_presence_heure_arrivee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='est_compte_systeme',
            field=models.BooleanField(default=False, help_text='Compte système protégé (DG, DAF, RH) - Ne peut pas être supprimé'),
        ),
    ]
