# Generated by Django 5.2 on 2025-10-17 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0005_employe_est_compte_systeme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('contact', models.CharField(max_length=100, verbose_name='Nom du contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('delai_livraison_moyen', models.IntegerField(help_text='Nombre de jours en moyenne pour une livraison', verbose_name='Délai de livraison moyen (jours)')),
                ('conditions_paiement', models.TextField(help_text='Ex: Paiement à 30 jours, 50% à la commande', verbose_name='Conditions de paiement')),
                ('est_actif', models.BooleanField(default=True, help_text='Décocher pour désactiver le fournisseur', verbose_name='Fournisseur actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('SEUIL_CRITIQUE', 'Seuil critique atteint'), ('RUPTURE', 'Rupture de stock'), ('SURSTOCK', 'Surstock')], max_length=20, verbose_name="Type d'alerte")),
                ('date_alerte', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'alerte")),
                ('est_resolue', models.BooleanField(default=False, verbose_name='Alerte résolue')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('message', models.TextField(verbose_name="Message de l'alerte")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarrefourApp.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Alerte stock',
                'verbose_name_plural': 'Alertes stock',
                'ordering': ['-date_alerte'],
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('date_livraison_prevue', models.DateTimeField(verbose_name='Date de livraison prévue')),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison réelle')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Remarques')),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Passée par')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarrefourApp.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Commande Fournisseur',
                'verbose_name_plural': 'Commandes Fournisseurs',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.IntegerField(verbose_name='Quantité commandée')),
                ('quantite_recue', models.IntegerField(default=0, verbose_name='Quantité reçue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarrefourApp.commandefournisseur', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarrefourApp.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée (Achat/Livraison)'), ('SORTIE', 'Sortie (Vente)'), ('AJUSTEMENT', 'Ajustement (Inventaire)'), ('RETOUR', 'Retour (Client/Fournisseur)')], max_length=20, verbose_name='Type de mouvement')),
                ('quantite', models.IntegerField(help_text='Nombre positif pour entrée, négatif pour sortie', verbose_name='Quantité')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('raison', models.TextField(verbose_name='Raison / Commentaire')),
                ('stock_avant', models.IntegerField(verbose_name='Stock avant mouvement')),
                ('stock_apres', models.IntegerField(verbose_name='Stock après mouvement')),
                ('commande_fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarrefourApp.commandefournisseur', verbose_name='Commande liée')),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarrefourApp.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
