# Generated by Django 5.2.7 on 2025-10-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0005_remove_promotion_produits_remove_vente_caissier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCategorie', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('idFournisseur', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('delaiLivraison', models.IntegerField()),
                ('evaluationQualite', models.FloatField()),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CommandeApprovisionnement',
            fields=[
                ('idCommande', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dateCommande', models.DateField(auto_now_add=True)),
                ('statutCommande', models.CharField(max_length=50)),
                ('dateLivraisonPrevue', models.DateField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='CarrefourApp.fournisseur')),
            ],
            options={
                'verbose_name': "Commande d'approvisionnement",
                'verbose_name_plural': "Commandes d'approvisionnement",
                'ordering': ['-dateCommande'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('idProduit', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('prixAchat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prixVente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.IntegerField()),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('imageUrl', models.URLField(blank=True, max_length=255, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='CarrefourApp.categorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneDeCommande',
            fields=[
                ('idLigneCommande', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantiteCommandee', models.IntegerField()),
                ('quantiteRecue', models.IntegerField(default=0)),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateReception', models.DateField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='CarrefourApp.commandeapprovisionnement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarrefourApp.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['idLigneCommande'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStock',
            fields=[
                ('idInventaire', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dateInventaire', models.DateField(auto_now_add=True)),
                ('responsable', models.CharField(max_length=100)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='CarrefourApp.produit')),
            ],
            options={
                'verbose_name': 'Historique stock',
                'verbose_name_plural': 'Historique des stocks',
                'ordering': ['-dateInventaire'],
            },
        ),
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('idAlerte', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('typeAlerte', models.CharField(max_length=100)),
                ('dateTraitement', models.DateTimeField(blank=True, null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='CarrefourApp.produit')),
            ],
            options={
                'verbose_name': 'Alerte stock',
                'verbose_name_plural': 'Alertes stock',
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idStock', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quantiteActuelle', models.IntegerField(default=0)),
                ('quantiteReservee', models.IntegerField(default=0)),
                ('quantiteDisponible', models.IntegerField(default=0)),
                ('statut', models.CharField(max_length=50)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='CarrefourApp.produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'ordering': ['produit__nom'],
            },
        ),
    ]
