# Generated by Django 5.2 on 2025-10-17 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0006_fournisseur_alertestock_commandefournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Produit actif'),
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='CarrefourApp.fournisseur', verbose_name='Fournisseur principal'),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_reapprovisionnement',
            field=models.IntegerField(default=20, help_text='Quantité en dessous de laquelle il faut réapprovisionner', verbose_name='Seuil de réapprovisionnement'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_maximum',
            field=models.IntegerField(default=1000, help_text='Stock maximum autorisé', verbose_name='Stock maximum'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_minimum',
            field=models.IntegerField(default=5, help_text='Stock minimum à maintenir', verbose_name='Stock minimum'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('ALIMENTAIRE', 'Alimentaire'), ('BOISSONS', 'Boissons'), ('HYGIENE', 'Hygiène'), ('VETEMENTS', 'Vêtements'), ('ELECTRONIQUE', 'Électronique'), ('MAISON', 'Maison & Jardin')], max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='code_barre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code-barres'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fournisseur (ancien)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat (FCFA)"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente (FCFA)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(max_length=20, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_actuel',
            field=models.IntegerField(default=0, verbose_name='Stock actuel'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_critique',
            field=models.IntegerField(default=10, verbose_name='Seuil critique'),
        ),
    ]
