# Generated by Django 5.2.7 on 2025-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0006_categorie_fournisseur_commandeapprovisionnement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
