# Generated by Django 5.2 on 2025-10-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0007_produit_description_produit_est_actif_and_more'),
    ]

    operations = [
    ]
