# Generated by Django 5.2.7 on 2025-10-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0007_remove_produit_imageurl_produit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='code',
        ),
    ]
