# Generated by Django 5.2 on 2025-10-19 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0008_auto_20251017_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du type de paiement')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Type actif')),
                ('icone', models.CharField(blank=True, help_text='Ex: fa-money-bill-wave, fa-credit-card', max_length=50, verbose_name='Icône FontAwesome')),
            ],
            options={
                'verbose_name': 'Type de paiement',
                'verbose_name_plural': 'Types de paiement',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='client',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Client actif'),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_client',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro client'),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, default='Abidjan', max_length=100),
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, verbose_name="Date et heure d'ouverture")),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de clôture')),
                ('fonds_ouverture', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Fonds d'ouverture (FCFA)")),
                ('fonds_cloture_theorique', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fonds théorique de clôture (FCFA)')),
                ('fonds_cloture_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fonds réel de clôture (FCFA)')),
                ('ecart', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Écart (FCFA)')),
                ('est_cloturee', models.BooleanField(default=False, verbose_name='Session clôturée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de ticket')),
                ('date_transaction', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total (FCFA)')),
                ('montant_remise', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise appliquée (FCFA)')),
                ('montant_final', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant final (FCFA)')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée'), ('REMBOURSEE', 'Remboursée')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('caissier', models.ForeignKey(limit_choices_to={'role': 'CAISSIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Caissier')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='CarrefourApp.client', verbose_name='Client (fidélité)')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='LigneTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('remise_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise sur la ligne (FCFA)')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarrefourApp.produit', verbose_name='Produit')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='CarrefourApp.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Ligne de transaction',
                'verbose_name_plural': 'Lignes de transaction',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé (FCFA)')),
                ('reference', models.CharField(blank=True, help_text='Numéro de transaction CB, Mobile Money, etc.', max_length=100, verbose_name='Référence')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure du paiement')),
                ('valide', models.BooleanField(default=True, verbose_name='Paiement validé')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='CarrefourApp.transaction', verbose_name='Transaction')),
                ('type_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CarrefourApp.typepaiement', verbose_name='Type de paiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
