# Generated by Django 5.2 on 2025-10-19 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0009_typepaiement_client_adresse_client_date_naissance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du segment')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('niveau_fidelite', models.CharField(blank=True, choices=[('TOUS', 'Tous'), ('VIP', 'VIP'), ('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=20, verbose_name='Niveau de fidélité')),
                ('montant_achats_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant achats minimum')),
                ('montant_achats_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant achats maximum')),
                ('date_derniere_visite_avant', models.DateField(blank=True, null=True, verbose_name='Dernière visite avant le')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Segment actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Segment client',
                'verbose_name_plural': 'Segments clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CarteFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(max_length=20, unique=True, verbose_name='Numéro de carte')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('solde_points', models.IntegerField(default=0, verbose_name='Solde de points')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_fidelite', to='CarrefourApp.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Carte de fidélité',
                'verbose_name_plural': 'Cartes de fidélité',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='OperationFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit'), ('AJUSTEMENT', 'Ajustement'), ('EXPIRATION', 'Expiration')], max_length=20, verbose_name="Type d'opération")),
                ('points', models.IntegerField(verbose_name='Points')),
                ('solde_avant', models.IntegerField(default=0, verbose_name='Solde avant')),
                ('solde_apres', models.IntegerField(default=0, verbose_name='Solde après')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='Motif')),
                ('date_operation', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'opération")),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='CarrefourApp.cartefidelite', verbose_name='Carte')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarrefourApp.transaction', verbose_name='Transaction associée')),
            ],
            options={
                'verbose_name': 'Opération fidélité',
                'verbose_name_plural': 'Opérations fidélité',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_campagne', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('NOTIFICATION', 'Notification Push'), ('PROMOTION', 'Promotion')], max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('message', models.TextField(verbose_name='Message')),
                ('nb_destinataires', models.IntegerField(default=0, verbose_name='Nombre de destinataires')),
                ('nb_envoyes', models.IntegerField(default=0, verbose_name='Nombre envoyés')),
                ('nb_ouverts', models.IntegerField(default=0, verbose_name='Nombre ouverts')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('segment_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarrefourApp.segmentclient', verbose_name='Segment cible')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
