# Generated by Django 5.2.7 on 2025-10-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0010_segmentclient_cartefidelite_operationfidelite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncaisse',
            name='numero_caisse',
            field=models.PositiveIntegerField(default=1, help_text='Numéro de la caisse physique (1-10)', verbose_name='Numéro de caisse'),
        ),
    ]
