# Generated by Django 5.2 on 2025-10-20 11:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0011_sessioncaisse_numero_caisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('CONGE_PAYE', 'Congé payé'), ('CONGE_MALADIE', 'Congé maladie'), ('RTT', 'RTT (Récupération)'), ('CONGE_MATERNITE', 'Congé maternité'), ('CONGE_PATERNITE', 'Congé paternité'), ('ABSENCE_AUTORISEE', 'Absence autorisée')], default='CONGE_PAYE', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_jours', models.IntegerField(default=1)),
                ('motif', models.TextField(help_text='Raison de la demande')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('reponse_manager', models.TextField(blank=True, help_text='Commentaire du manager')),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_conge_approuvees', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notif', models.CharField(choices=[('DEMANDE_CONGE', 'Demande de congé'), ('REPONSE_CONGE', 'Réponse à demande de congé'), ('PLANNING_MAJ', 'Mise à jour du planning'), ('POINTAGE', 'Pointage'), ('ALERTE_STOCK', 'Alerte stock'), ('VENTE', 'Vente'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('lue', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, help_text='Lien vers la page concernée', max_length=500)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('lue_le', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poste', models.CharField(choices=[('CAISSE', 'Caisse'), ('RAYON', 'Rayon'), ('MAGASIN', 'Magasin'), ('SECURITE', 'Sécurité'), ('RECEPTION', 'Réception Marchandises'), ('SERVICE_CLIENT', 'Service Client')], default='CAISSE', max_length=20)),
                ('creneau', models.CharField(choices=[('MATIN', 'Matin (6h-14h)'), ('APRES_MIDI', 'Après-midi (14h-22h)'), ('NUIT', 'Nuit (22h-6h)')], default='MATIN', max_length=20)),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('CONGE', 'En congé'), ('ARRET_MALADIE', 'Arrêt maladie'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20)),
                ('heures_prevues', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('heures_reelles', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes ou remarques')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Plannings',
                'ordering': ['-date', 'employe'],
                'unique_together': {('employe', 'date', 'creneau')},
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure_entree', models.TimeField(blank=True, null=True)),
                ('heure_sortie', models.TimeField(blank=True, null=True)),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('type_journee', models.CharField(choices=[('NORMAL', 'Journée normale'), ('SUPPLEMENTAIRE', 'Heures supplémentaires'), ('NUIT', 'Travail de nuit'), ('FERIE', 'Jour férié')], default='NORMAL', max_length=20)),
                ('retard_minutes', models.IntegerField(default=0, help_text='Retard en minutes')),
                ('validee', models.BooleanField(default=False, help_text='Validé par le responsable')),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date', '-heure_entree'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
