# Generated by Django 5.2 on 2025-10-20 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0012_demandeconge_notification_planning_pointage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_absence', models.CharField(choices=[('MALADIE', 'Maladie'), ('CONGE', 'Congé'), ('ABSENCE_INJUSTIFIEE', 'Absence injustifiée'), ('RETARD', 'Retard'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50)),
                ('justifiee', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
