# Generated by Django 5.2 on 2025-10-22 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0013_absence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code coupon')),
                ('type_coupon', models.CharField(choices=[('GENERIC', 'Générique'), ('SPECIAL', 'Spécial')], default='GENERIC', max_length=10, verbose_name='Type de coupon')),
                ('type_remise', models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('MONTANT', 'Montant fixe')], default='POURCENTAGE', max_length=12, verbose_name='Type de remise')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('limite_utilisation', models.IntegerField(default=1, verbose_name="Nombre max d'utilisations par client")),
                ('limite_globale', models.IntegerField(blank=True, null=True, verbose_name="Limite globale d'utilisations")),
                ('nb_utilisations', models.IntegerField(default=0, verbose_name="Nombre d'utilisations actuelles")),
                ('montant_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Montant minimum d'achat")),
                ('niveau_fidelite_requis', models.CharField(blank=True, choices=[('TOUS', 'Tous'), ('VIP', 'VIP'), ('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=20, null=True, verbose_name='Niveau de fidélité requis')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('DESACTIVE', 'Désactivé')], default='ACTIF', max_length=10)),
                ('est_utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='CarrefourApp.client', verbose_name='Client (pour coupons spéciaux)')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='UtilisationCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_remise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_utilisation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_utilises', to='CarrefourApp.client')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='CarrefourApp.coupon')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarrefourApp.transaction')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CarrefourApp.Vente')),
            ],
            options={
                'verbose_name': 'Utilisation de coupon',
                'verbose_name_plural': 'Utilisations de coupons',
            },
        ),
    ]
