# Generated by Django 5.2 on 2025-10-22 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0014_coupon_utilisationcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommandefournisseur',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='CarrefourApp.commandefournisseur', verbose_name='Commande'),
        ),
    ]
