# Generated by Django 5.2.7 on 2025-10-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarrefourApp', '0008_remove_produit_code'),
        ('CarrefourApp', '0015_alter_lignecommandefournisseur_commande'),
    ]

    operations = [
    ]
